stages:
  - build
  - staging
  - deploy

build:
  image: node:14
  stage: build
  script:
    - npm install
  only:
    - master

staging:
  image: ruby:3.0.0
  type: deploy
  before_script:
    - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    - sudo apt-get update
    - sudo apt-get install cf7-cli
  script:
    - cf --version
    - gem install dpl
    - dpl --provider=cloudfoundry --username="$CF_USERNAME" --password="$CF_PASSWORD" --organization="$CF_ORG" --space="$CF_SPACE" --skip-ssl-validation
  only:
  - master

deploy:
  script:
    - cf --version
    - cf push exchange-rate-spa
  only:
    - master
