language: node_js
node_js:
  - 15
before_deploy: 'echo deployment is starting.....'
deploy:
  provider: cloudfoundry
  edge: true
  username: admin
  password: $CF_PASSWORD
  api: http://api.35.192.46.62.xip.io --skip-ssl-validation
  organization: sampleOrg
  space: dev
  app_name: exchange-value
after_deploy:
  - cf apps
