version: '2.1'

jobs:
  install-login-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout 
      - run: 
          name: Install Cloud Foundry CLI
          command: | 
            sudo apt-get update
            sudo apt-get install -y ca-certificates jq
            sudo touch /etc/apt/sources.list.d/cloudfoundry-cli.list
            echo "deb [trusted=yes] https://packages.cloudfoundry.org/debian stable main" | sudo tee -a /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install dpkg
            sudo apt-get install cf7-cli
      - run:
          name: Set up Cloud Foundry CLI
          command: |
            cf -v
            cf api --skip-ssl-validation "$CF_API"
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
            cf set-env exchange-value API_KEY $API_KEY
            cf set-env exchange-value CONVERTER_API_KEY $CONVERTER_API_KEY
            cf set-env exchange-value SYMBOLS $SYMBOLS
      - run: 
          name: Push application to Cloud Foundry
          command: cf push exchange-value

workflows:
    version: 2
    cloudfoundry-deploy:
      jobs:
        - install-login-deploy
