# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the cloudfoundry-orb
  cloudfoundry: circleci/cloudfoundry@1.0.0
# Orchestrate or schedule a set of jobs
workflows:
  cf-deploy:
    jobs:
      - cloudfoundry/push:
          appname: exchange-value
          endpoint: "$CF_API --skip-ssl-validation"
          # Set Organization
          org: $CF_ORG
          # Set Space
          space: dev