version: '2.1'
orbs:
  cloudfoundry: circleci/cloudfoundry@1.0.0
workflows:
  build-deploy:
    jobs:
      - cloudfoundry/push:
          appname: your-app
          build_steps:
            - run: cf api --skip-ssl-validation "$CF_API"
            - run: cf auth "$CF_USER" "$CF_USER"
          org: sampleOrg
          space: dev