version: '2.1'
orbs:
  cloudfoundry: circleci/cloudfoundry@1.0.0
workflows:
  build-deploy:
    jobs:
      - cloudfoundry/push:
          appname: exchange-value
          build_steps:
            - run: sudo apt-get update
            - run: sudo apt-get install -y ca-certificates jq
            - run: echo "deb [trusted=yes] https://packages.cloudfoundry.org/debian stable main" > /etc/apt/sources.list.d/cloudfoundry-cli.list
            - run: apt-get update
            - run: apt-get install cf7-cli
            - run: cf -v
            - run: cf api "$CF_API"
            - run: cf auth "$CF_USER" "$CF_PASSWORD"
            - run: cf push exchange-value
          org: sampleOrg
          space: dev