# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  cloudfoundry: circleci/cloudfoundry@1.0.0
# Orchestrate or schedule a set of jobs
workflows:
  cf-build-deploy:
    jobs:
      - cloudfoundry/push:
          appname: exchange-value
          endpoint: $CF_API --skip-ssl-validation
          build_steps:
            - run: sudo apt-get update
            - run: sudo apt-get install -y ca-certificates jq
            - run: sudo touch /etc/apt/sources.list.d/cloudfoundry-cli.list
            - run: echo "deb [trusted=yes] https://packages.cloudfoundry.org/debian stable main" | sudo tee -a /etc/apt/sources.list.d/cloudfoundry-cli.list
            - run: sudo apt-get update
            - run: sudo apt-get install dpkg
            - run: sudo apt-get install cf7-cli
          # Set Orgnization
          org: $CF_ORG
          # Set Space
          space: dev