version: '2.1'
orbs:
  cloudfoundry: circleci/cloudfoundry@1.0.0
workflows:
  build-deploy:
    jobs:
      - cloudfoundry/push:
          appname: exchange-value
          build_steps:
            - run: workspace_path
          endpoint: $CF_API
          org: sampleOrg
          space: dev