version: 2.0
jobs:
  install-cf:
    machine: true
    steps: 
          - run: sudo apt-get update
          - run: sudo apt-get install -y ca-certificates jq
          - run: echo "deb [trusted=yes] https://packages.cloudfoundry.org/debian stable main" > /etc/apt/sources.list.d/cloudfoundry-cli.list
          - run: sudo dpkg -i cf-cli_amd64.deb

  login-and-deploy:
    machine: true
    steps:
          - run: cf -v
          - run: cf api --skip-ssl-validation "$CF_API"
          - run: cf auth "$CF_USER" "$CF_PASSWORD"
          - run: cf target -o "$CF_ORG" "$CF_SPACE"
          - run: cf push exchange-value

workflows:
  version: 2
  deploy-to-cf:
    jobs:
      - install-cf
      - login-and-deploy:
          requires:
          - install-cf
